{{- if .Values.sharedConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hatchet-shared-config
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.caddy.annotations }}
  annotations:
{{ toYaml .Values.caddy.annotations | indent 4 }}
{{- end }}
type: Opaque
data:
{{- if .Values.postgres.enabled }}
  DATABASE_URL: "{{ printf "postgres://%s:%s@%s-postgres:%d/%s?sslmode=%s" .Values.postgres.auth.username .Values.postgres.auth.password .Release.Name .Values.postgres.primary.service.ports.postgresql .Values.postgres.auth.database (ternary "require" "disable" .Values.postgres.tls.enabled) | b64enc }}"
  DATABASE_POSTGRES_HOST: "{{ printf "%s-postgres" .Release.Name | b64enc }}"
  DATABASE_POSTGRES_PORT: "{{ .Values.postgres.primary.service.ports.postgresql | quote | b64enc }}"
  DATABASE_POSTGRES_USERNAME: "{{ .Values.postgres.auth.username | quote | b64enc }}"
  DATABASE_POSTGRES_PASSWORD: "{{ .Values.postgres.auth.password | quote | b64enc }}"
  DATABASE_POSTGRES_DB_NAME: "{{ .Values.postgres.auth.database | quote | b64enc }}"
  DATABASE_POSTGRES_SSL_MODE: "{{ (ternary "require" "disable" .Values.postgres.tls.enabled) | quote | b64enc }}"
{{- end }}
{{- if .Values.rabbitmq.enabled }}
  SERVER_TASKQUEUE_RABBITMQ_URL: "{{ printf "amqp://%s:%s@%s-rabbitmq:%d/" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Release.Name .Values.rabbitmq.primary.service.ports.amqp | b64enc }}"
{{- end }}
  SERVER_URL: "{{ .Values.sharedConfig.serverUrl | b64enc }}"
  SERVER_AUTH_COOKIE_DOMAIN: "{{ .Values.sharedConfig.serverAuthCookieDomain | b64enc }}"
  SERVER_AUTH_COOKIE_INSECURE: "{{ .Values.sharedConfig.serverAuthCookieInsecure | b64enc }}"
  SERVER_AUTH_SET_EMAIL_VERIFIED: "{{ .Values.sharedConfig.serverAuthSetEmailVerified | b64enc }}"
  SERVER_AUTH_BASIC_AUTH_ENABLED: "{{ .Values.sharedConfig.serverAuthBasicAuthEnabled | b64enc }}"
  SERVER_GRPC_BROADCAST_ADDRESS: "{{ .Values.sharedConfig.grpcBroadcastAddress | b64enc }}"
  ADMIN_EMAIL: "{{ .Values.sharedConfig.defaultAdminEmail | b64enc }}"
  ADMIN_PASSWORD: "{{ .Values.sharedConfig.defaultAdminPassword | b64enc }}"
  SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
  SERVER_GRPC_INSECURE: {{ .Values.sharedConfig.serverGrpcInsecure | b64enc }}
{{- range $key, $value := .Values.sharedConfig.env }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}
