apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hatchet.fullname" . }}
data:
  server.yaml: |
{{ toYaml .Values.config.server | indent 4 }}
  database.yaml: |
{{ toYaml .Values.config.database | indent 4 }}
  temporal.yaml: |
{{ toYaml .Values.config.temporal | indent 4 }}
  shared.yaml: |
{{ toYaml .Values.config.shared | indent 4 }}
  background_worker.yaml: |
{{ toYaml .Values.config.background_worker | indent 4 }}
  runner_worker.yaml: |
{{ toYaml .Values.config.runner_worker | indent 4 }}
