apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hatchet.fullname" . }}
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "hatchet.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
      labels:
{{- include "hatchet.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "hatchet.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      initContainers:
        name: config-generator
        image: "ghcr.io/hatchet-dev/hatchet/hatchet-admin:v0.1.0-alpha.1"
        imagePullPolicy: Always
        command: [
          "/hatchet/hatchet-admin", 
          "quickstart", 
          "--config", 
          "/hatchet/config", 
          "--cert-dir", 
          "/hatchet/data/config/generated/certs", 
          "--generated-config-dir", 
          "/hatchet/data/config/generated", 
          "--skip",
          "static",
          "--overwrite=false",
        ]
        volumeMounts:
        - name: data-volume
          mountPath: /hatchet/data
        - name: config-volume
          mountPath: "/hatchet/config"
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
{{- if .Values.initContainers }}
{{- range $key, $value := .Values.initContainers }}
      - name: "{{ $key }}"
{{ toYaml $value | indent 8 }}
{{- end }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ required "Please set a value for .Values.image.tag" .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/hatchet/hatchet-server"]
        {{- if .Values.commandline.args }}
        args:
{{ toYaml .Values.commandline.args | indent 10 }}
        {{- else }}
        args: []
        {{- end }}
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: {{ template "hatchet.name" . }}
          protocol: TCP
        - containerPort: {{ .Values.service.internalTemporalPort }}
          name: temporal
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: data-volume
          mountPath: /hatchet/data
      - name: {{ .Chart.Name }}-runner-worker
        image: "{{ .Values.runnerWorker.image.repository }}:{{ required "Please set a value for .Values.image.tag" .Values.runnerWorker.image.tag }}"
        imagePullPolicy: {{ .Values.runnerWorker.image.pullPolicy }}
        command: ["/hatchet/hatchet-runner-worker"]
        {{- if .Values.runnerWorker.commandline.args }}
        args:
{{ toYaml .Values.runnerWorker.commandline.args | indent 10 }}
        {{- else }}
        args: []
        {{- end }}
        env:
        {{- range $key, $value := .Values.runnerWorker.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        resources:
{{ toYaml .Values.runnerWorker.resources | indent 10 }}
        volumeMounts:
        - name: data-volume
          mountPath: /hatchet/data
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
{{- with .Values.extraContainers }}
{{ tpl . $ | indent 6 }}
{{- end }}
{{- range .Values.extraConfigMapMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ .subPath }}
{{- end }}
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
{{- end }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data-pvc"
        - name: config-volume
          configMap:
            name: {{ template "hatchet.fullname" . }}
{{- range .Values.extraConfigMapMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
---
{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "hatchet.fullname" . }}
spec:
  {{ toYaml .Values.podDisruptionBudget }}
  selector:
    matchLabels:
  {{- include "hatchet.selectorLabels" . | nindent 6 }}
{{- end }}
