{{- if .Values.sharedEnvEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hatchet-shared-config
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.caddy.annotations }}
  annotations:
{{ toYaml .Values.caddy.annotations | indent 4 }}
{{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}